FROM anapsix/alpine-java
COPY ./poc-word-operations/target/poc-word-operations-0.0.1-SNAPSHOT.jar /home/poc-word-operations-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","/home/poc-word-operations-0.0.1-SNAPSHOT.jar"]
