---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: _APP_NAME_-deployment
  namespace: _NAMESPACE_NAME_
  labels:
    app: _APP_NAME_-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: _APP_NAME_-deployment
  template:
    metadata:
      labels:
        app: _APP_NAME_-deployment
    spec:
      containers:
      - name: _APP_NAME_-container
        image: _IMAGE_NAME_:_IMAGE_TAG_
        imagePullPolicy: Always
        volumeMounts:
        - name: _APP_NAME_-config-volume
          mountPath: /app/conf/application.properties
          subPath: application.properties
        ports:
        - containerPort: _IMAGE_PORT_
      volumes:
        - name: _APP_NAME_-config-volume
          configMap:
            name: _APP_NAME_-config
            items:
            - key: application.properties
              path: application.properties
