kind: Deployment
apiVersion: apps/v1
metadata:
  name: space-pdf-generator-deployment
  namespace: space-alpha-apps
  uid: e03cf340-3fb7-49d9-9945-3be06bc4fe71
  resourceVersion: ‘701635322’
  generation: 6
  creationTimestamp: ‘2022-02-24T10:38:12Z’
  annotations:
    deployment.kubernetes.io/revision: ‘6’
    kubectl.kubernetes.io/last-applied-configuration: >
      {“apiVersion”:“apps/v1",“kind”:“Deployment”,“metadata”:{“annotations”:{},“name”:“space-pdf-generator-deployment”,“namespace”:“space-alpha-apps”},“spec”:{“replicas”:1,“selector”:{“matchLabels”:{“app”:“space-pdf-generator-deployment”}},“template”:{“metadata”:{“labels”:{“app”:“space-pdf-generator-deployment”}},“spec”:{“containers”:[{“image”:“915076882459.dkr.ecr.us-east-1.amazonaws.com/space-poc:pdf-generator-service”,“imagePullPolicy”:“Always”,“name”:“space-pdf-generator-container”,“ports”:[{“containerPort”:8080,“protocol”:“TCP”}]}]}}}}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space-pdf-generator-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: space-pdf-generator-deployment
    spec:
      volumes:
        - name: space-pdf-generator-config-volume
          configMap:
            name: space-pdf-generator-config
            items:
              - key: application.properties
                path: application.properties
            defaultMode: 420
      containers:
        - name: space-pdf-generator-container
          image: >-
            915076882459.dkr.ecr.us-east-1.amazonaws.com/space-poc:pdf-generator-service
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: space-pdf-generator-config-volume
              mountPath: /app/conf/application.properties
              subPath: application.properties
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 6
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: ‘True’
      lastUpdateTime: ‘2022-03-04T11:43:53Z’
      lastTransitionTime: ‘2022-02-24T10:38:12Z’
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet “space-pdf-generator-deployment-bcd4d494d” has successfully
        progressed.
    - type: Available
      status: ‘True’
      lastUpdateTime: ‘2022-03-12T08:14:03Z’
      lastTransitionTime: ‘2022-03-12T08:14:03Z’
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.